#if PLATFORM_GLES
#include <GLES2/gl2.h>
#include <GLES2/gl2ext.h>

#if GL_GLEXT_PROTOTYPES == 0
#if GL_OES_mapbuffer
extern PFNGLMAPBUFFEROESPROC         glMapBufferOES;
extern PFNGLUNMAPBUFFEROESPROC       glUnmapBufferOES;
extern PFNGLGETBUFFERPOINTERVOESPROC glGetBufferPointervOES;

#endif
#if PLATFORM_GL_OES_vertex_array_object
extern PFNGLBINDVERTEXARRAYOESPROC    glBindVertexArrayOES;
extern PFNGLDELETEVERTEXARRAYSOESPROC glDeleteVertexArraysOES;
extern PFNGLGENVERTEXARRAYSOESPROC    glGenVertexArraysOES;
extern PFNGLISVERTEXARRAYOESPROC      glIsVertexArrayOES;

#endif
#if PLATFORM_GL_KHR_debug
extern PFNGLDEBUGMESSAGECONTROLKHRPROC  glDebugMessageControlKHR;
extern PFNGLDEBUGMESSAGEINSERTKHRPROC   glDebugMessageInsertKHR;
extern PFNGLDEBUGMESSAGECALLBACKKHRPROC glDebugMessageCallbackKHR;
extern PFNGLGETDEBUGMESSAGELOGKHRPROC   glGetDebugMessageLogKHR;
extern PFNGLPUSHDEBUGGROUPKHRPROC       glPushDebugGroupKHR;
extern PFNGLPOPDEBUGGROUPKHRPROC        glPopDebugGroupKHR;
extern PFNGLOBJECTLABELKHRPROC          glObjectLabelKHR;
extern PFNGLGETOBJECTLABELKHRPROC       glGetObjectLabelKHR;
extern PFNGLOBJECTPTRLABELKHRPROC       glObjectPtrLabelKHR;
extern PFNGLGETOBJECTPTRLABELKHRPROC    glGetObjectPtrLabelKHR;
extern PFNGLGETPOINTERVKHRPROC          glGetPointervKHR;

#endif
#endif // GL_GLEXT_PROTOTYPES
#endif // PLATFORM_GLES
